minimumReleaseAgeExclude:
  - '@biomejs/biome@2.5.7'
  - '@biomejs/cli-darwin-arm64@2.5.7'
  - '@biomejs/cli-darwin-x64@2.5.7'
  - '@biomejs/cli-linux-arm64-musl@2.5.7'
  - '@biomejs/cli-linux-arm64@2.5.7'
  - '@biomejs/cli-linux-x64-musl@2.5.7'
  - '@biomejs/cli-linux-x64@2.5.7'
  - '@biomejs/cli-win32-arm64@2.5.7'
  - '@biomejs/cli-win32-x64@2.5.7'
  - '@rsbuild/core@2.1.10'
  - '@rslint/core@0.7.3'
  - '@rslint/native-darwin-arm64@0.7.3'
  - '@rslint/native-darwin-x64@0.7.3'
  - '@rslint/native-linux-arm64-gnu@0.7.3'
  - '@rslint/native-linux-arm64-musl@0.7.3'
  - '@rslint/native-linux-x64-gnu@0.7.3'
  - '@rslint/native-linux-x64-musl@0.7.3'
  - '@rslint/native-win32-arm64-msvc@0.7.3'
  - '@rslint/native-win32-x64-msvc@0.7.3'
  - '@rspack/binding-darwin-arm64@2.1.8'
  - '@rspack/binding-darwin-x64@2.1.8'
  - '@rspack/binding-linux-arm64-gnu@2.1.8'
  - '@rspack/binding-linux-arm64-musl@2.1.8'
  - '@rspack/binding-linux-riscv64-gnu@2.1.8'
  - '@rspack/binding-linux-riscv64-musl@2.1.8'
  - '@rspack/binding-linux-x64-gnu@2.1.8'
  - '@rspack/binding-linux-x64-musl@2.1.8'
  - '@rspack/binding-wasm32-wasi@2.1.8'
  - '@rspack/binding-win32-arm64-msvc@2.1.8'
  - '@rspack/binding-win32-ia32-msvc@2.1.8'
  - '@rspack/binding-win32-x64-msvc@2.1.8'
  - '@rspack/binding@2.1.8'
  - '@rspack/core@2.1.8'
  - '@rstest/adapter-rsbuild@0.11.6'
  - '@rstest/core@0.11.6'
  - '@vue/compiler-core@3.5.41'
  - '@vue/compiler-dom@3.5.41'
  - '@vue/compiler-sfc@3.5.41'
  - '@vue/compiler-ssr@3.5.41'
  - '@vue/reactivity@3.5.41'
  - '@vue/runtime-core@3.5.41'
  - '@vue/runtime-dom@3.5.41'
  - '@vue/server-renderer@3.5.41'
  - '@vue/shared@3.5.41'
  - vue@3.5.41
